#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Mission 1 - Moving forward
- This program will cause the robot to drive toward Starting Point 2.
- Your robot will wait for 2 seconds before beginning, move forward at half power for 2 rotations
	of the right encoder (a sensor that detects how much your wheels have spun), and then stop.
*	Please note that the values in this program were written for Mammalbot using a high-end computer.
	You may need to adjust the values in this program for your computer.

Robot Model: Mammalbot

[I/O Port]          [Name]              [Type]               [Description]
Motor Port 2        rightMotor          Motor w/ Encoder     Right side motor
Motor Port 3        leftMotor           Motor w/ Encoder     Left side motor
Digital Port 11			touchSensor					Touch 				 			 Front robot bumper
Digital Port 8 			sonarSensor					Sonar 				 			 Front robot sensor
Analog Port 4 			lightSensor					Color Sensor  		 	 Bottom Facing Color Sensor
----------------------------------------------------------------------------------------------------*/

void turn(int degree);

void moveForward(float distance) {
	//Wait for 2 second before moving forward
	wait1Msec(1000);

	int rotationCount = distance * 200;

	//Reset Motor Encoders
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	//Move forward at half speed, for 2 rotations of the right encoder
	while(getMotorEncoder(rightMotor) < rotationCount)
	{
		motor[rightMotor] = 50;
		motor[leftMotor] = 50;
	}

	//Stop
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void turnLeft() {
	turn(-90);
}

void turnRight() {
	turn(90);
}

void turn(int degree) {
	if (degree == 0) return;

	//Wait for half second before moving forward
	wait1Msec(1000);

	int direction = degree > 0 ? 1 : -1;

	float rotateCount = fabs(148.0 / 90 * degree);

	//Reset Motor Encoders
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	//Move forward at half speed, for 2 rotations of the right encoder
	while(fabs(getMotorEncoder(leftMotor)) < rotateCount)
	{
		motor[rightMotor] = -50 * direction;
		motor[leftMotor] = 50 * direction;
	}

	//Stop
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

task main()
{
	moveForward(6);
	turnLeft();
	moveForward(7);
	turnRight();
	moveForward(16.5);
}
