#pragma config(Motor,  port6,           liftMotor2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftMotor3,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftMotor4,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftMotor1,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setLiftMotor(int speed) {
		motor[liftMotor1] = speed;
		motor[liftMotor2] = speed;
		motor[liftMotor3] = speed;
		motor[liftMotor4] = speed;
}

task main()
{
	while(true){
		if (vexRT[Btn6D] == 1 || vexRT[Btn6DXmtr2] == 1) {
			setLiftMotor(40);
		}
		else if (vexRT[Btn6U] == 1 || vexRT[Btn6UXmtr2] == 1) {
			setLiftMotor(-128);
		}
		else {
			setLiftMotor(0);
		}
	}
}
